#!/bin/bash

sudo apt update

if ! [ -x "$(command -v tasksel)" ]; then
 sudo apt install tasksel
fi
sudo tasksel install lamp-server

sudo apt install phpmyadmin

echo "  "

echo "(c) Copyright by Mr CaT 2017 for Linuxoids"

