#!/bin/bash

printf "%s \n" "The scripts for installing default soft, by Mr CaT"

sudo apt-get update

printf "%s \n" "Installing GIT..."

sudo apt-get install git

printf "%s \n" "Installing Mercurial | BitBucket's GIT client..."

sudo apt-get install mercurial

printf "%s \n" "Installing VLC Media player..."

sudo apt-get install vlc

printf "%s \n" "Installing Synaptic..."

sudo apt-get install synaptic

printf "%s \n" "Installing SQL MAP..."

sudo apt-get install sqlmap

printf "%s \n" "Installing Pulse Audio Equalizer..."

sudo apt-add-repository ppa:nilarimogard/webupd8

sudo apt-get update

sudo apt-get install pulseaudio-equalizer

printf "%s \n" "Installing Telegram Desktop..."

sudo add-apt-repository ppa:atareao/telegram

sudo apt-get update

sudo apt-get install telegram

printf "%s \n" "Installing Chromium Browser..."

sudo apt-get install chromium-browser

printf "%s \n" "Installing XDMAN..."

wget -c "http://downloads.sourceforge.net/project/xdman/xdman.deb?r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fxdman%2F&ts=1478419832&use_mirror=heanet" -O xdman.deb

sudo dpkg -i xdman.deb

sudo apt-get install -f 

printf "%s \n" "Installing Discord..."

wget https://discordapp.com/api/download?platform=linux&format=deb -O discord.deb

sudo dpkg -i discord.deb

printf "%s \n" "Installing Sublime Text 3..."

sudo add-apt-repository ppa:webupd8team/sublime-text-3

sudo apt-get update

sudo apt-get install sublime-text-installer

printf "%s \n" "-------------------------------------------------------------------" "The script had been written by Mr CaT" "Special thanks to Mr CaT" "Mr CaT in telegram: @mrcat323"
